import localFont from 'next/font/local'
import type { Metadata } from "next";
import "./globals.css";
import { Lexend, Courier_Prime } from "next/font/google";
import { cn } from "@/lib/utils";

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

const sansation = localFont({
  src: [
    { path: '../fonts/Sansation-Light.ttf', weight: '300', style: 'normal' },
    { path: '../fonts/Sansation-Regular.ttf', weight: '400', style: 'normal' },
    { path: '../fonts/Sansation-Bold.ttf', weight: '700', style: 'normal' },
  ],
  variable: '--font-sansation',
})

const courierPrime = Courier_Prime({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-courier-prime",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "font-sans",
        lexend.variable,
        sansation.variable,
        courierPrime.variable
      )}
    >
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}